name: Lighthouse audit
on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://lucagrementieri.github.io/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
